### ISSUE TITLE
How to change the default tab size to 4?

### ISSUE THREAD

**Issue by henrywright** [GoogleChrome/chromedeveditor#3861]
The default tab size seems to be 2 spaces. Any idea how I can change this to 4?

**Comment by rchassereau** [comment]
This seems like it should be added to a preference menu.  If you download dart and get a copy of the repo you can set this yourself.  The settings aren't as granular as eclipse is, but I expect this may be added soon.  I'm currently on the 0.0.17 repo, due to autocomplete issues.  If you modify line 260 of ace.dart, which reads:

session.tabSize = 2;

just set it to 4 and you will have 4 spaces instead...this only affects the editing mode (thus doesn't apply to previous tab spaces).

**Comment by henrywright** [comment]
@rchassereau thanks for the info. I'm running the editor as a Chromium app on Ubuntu 14.04. Do you know where I can find the ace.dart file?

**Comment by rchassereau** [comment]
@henrywright it's in the web/ide/lib folder.  I would recommend downloading the repo, and navigating to this path with in it and performing the change.  You can load the app externally if you enable developer mode in chrome extensions.

**Comment by henrywright** [comment]
No luck finding that folder unfortunately. I think perhaps because I'm using the app as a Chromium extension.

**Comment by henrywright** [comment]
Found the folder thanks to this [answer](http://askubuntu.com/a/26785/353018) on Ask Ubuntu. Problem is, making the change you suggested has no effect
