### ISSUE TITLE
Still the Best editor,

### ISSUE THREAD

**Issue by stlcool** [GoogleChrome/chromedeveditor#4092]
It's like a secret. GOOD JOB DEVS.

**Comment by darthwalsh** [comment]
I remember a few years ago, I was trying out both Chrome Dev Editor, and Visual Studio Code. I was really impressed with Google's vision for Chrome apps being the next generation of cross-platform apps, and saw the pure-javascript implementations of an editor, git client, and HTTP server demonstrating the power of this platform. You could even package the chrome app onto Android (using Cordova?). Since then, it seems that VS Code has really grown to dominate the developer community, while Chrome Dev Editor lost investment :\

**Comment by gio1135** [comment]
Well said @darthwalsh

**Comment by oscarvalenzuelab** [comment]
+1
